//
//  DeveloperPreview.swift
//  Airbnb_2.0
//
//  Created by Yery Castro on 14/11/23.
//

import Foundation

class DeveloperPreview {
    static let shared = DeveloperPreview()
    
    var listings: [Listing] = [
    
        .init(id: NSUUID().uuidString,
              ownerUid: NSUUID().uuidString,
              ownerName: "John Smith",
              ownerImageUrl: "male-profile-photo",
              numberOfBedrooms: 4,
              numberOfBathrooms: 3,
              numberOfGuests: 4,
              numberOfBeds: 4,
              pricePerNight: 567,
              latitude: 25.7850,
              longitude: -80.1936, 
              imageURLs: ["listing-3", "listing-1", "listing-5", "listing-4"],
              addres: "124 Main St",
              city: "Miami",
              state: "Florida",
              title: "Miami Villa",
              rating: 4.86,
              features: [.selfCheckIn, .superHost],
              amenities: [.wifi, .alarmSystem, .balcony, .laundry, .tv],
              type: .villa),
        .init(id: NSUUID().uuidString,
              ownerUid: NSUUID().uuidString,
              ownerName: "Michael Smith",
              ownerImageUrl: "male-profile-photo",
              numberOfBedrooms: 3,
              numberOfBathrooms: 3,
              numberOfGuests: 4,
              numberOfBeds: 4,
              pricePerNight: 435,
              latitude: 25.7834,
              longitude: -80.1945, 
              imageURLs: ["listing-2", "listing-5", "listing-3", "listing-4"],
              addres: "234 Main St",
              city: "Los Angeles",
              state: "California",
              title: "LA Beach",
              rating: 3.78,
              features: [.selfCheckIn, .superHost],
              amenities: [.wifi, .alarmSystem, .tv],
              type: .townHouse),
        .init(id: NSUUID().uuidString,
              ownerUid: NSUUID().uuidString,
              ownerName: "George Satos",
              ownerImageUrl: "male-profile-photo",
              numberOfBedrooms: 1,
              numberOfBathrooms: 3,
              numberOfGuests: 4,
              numberOfBeds: 4,
              pricePerNight: 321,
              latitude: 25.7345,
              longitude: -80.1946,
              imageURLs: ["listing-2", "listing-1", "listing-3", "listing-5"],
              addres: "300 Main St",
              city: "Los Angeles",
              state: "California",
              title: "LA Park",
              rating: 4.86,
              features: [.selfCheckIn, .superHost],
              amenities: [.wifi, .alarmSystem, .balcony, .laundry, .tv],
              type: .house),
        .init(id: NSUUID().uuidString,
              ownerUid: NSUUID().uuidString,
              ownerName: "Angel Lou",
              ownerImageUrl: "male-profile-photo",
              numberOfBedrooms: 5,
              numberOfBathrooms: 3,
              numberOfGuests: 4,
              numberOfBeds: 2,
              pricePerNight: 700,
              latitude: 25.7840,
              longitude: -80.1943,
              imageURLs: ["listing-2", "listing-1", "listing-3", "listing-5"],
              addres: "345 Main St",
              city: "Miami",
              state: "Florida",
              title: "Miami House",
              rating: 4.86,
              features: [.selfCheckIn, .superHost],
              amenities: [.wifi, .alarmSystem, .balcony, .laundry, .tv, .office, .pool],
              type: .villa),
    
    ]
}
